language: cpp
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
sudo: required
os: linux
dist: trusty
group: stable

matrix:
  include:
    - addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
            - ubuntu-toolchain-r-test
            - deadsnakes #python3.6
            - sourceline: 'ppa:ricotz/toolchain' #meson & ninja
          packages:
            - clang-6.0
            - lld-6.0
            - gcc-multilib
            - g++-multilib
            - python3.6
            - meson
            - ninja-build
            - lib32z1-dev
            - lib32stdc++6
            - libc6-dev-i386
            - linux-libc-dev
      env:
        - CLANG_VERSION=6
        - COMPILERS="export CC=clang-6.0 CXX=clang++-6.0"

    - addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
            - deadsnakes #python3.6
            - sourceline: 'ppa:ricotz/toolchain' #meson & ninja
          packages:
            - clang-5.0
            - lld-5.0
            - gcc-multilib
            - g++-multilib
            - python3.6
            - meson
            - ninja-build
            - lib32z1-dev
            - lib32stdc++6
            - libc6-dev-i386
            - linux-libc-dev
      env:
          - CLANG_VERSION=5
          - COMPILERS="export CC=clang-5.0 CXX=clang++-5.0"
          
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes #python3.6
            - sourceline: 'ppa:ricotz/toolchain' #meson & ninja
          packages:
            - gcc-7
            - g++-7
            - gcc-7-multilib
            - g++-7-multilib
            - python3.6
            - meson
            - ninja-build
            - lib32z1-dev
            - lib32stdc++6
            - libc6-dev-i386
            - linux-libc-dev
      env:
        - GCC_VERSION=7
        - COMPILERS="export CC=gcc-7 CXX=g++-7"

before_script:
    - eval ${COMPILERS}
    - travis/prepare.sh
script:
    - eval ${COMPILERS}
    - travis/build.sh
