version: 0.0.1-{build}
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
platform: x64
build:
  parallel: true
  verbosity: detailed
install:
  - git submodule update --init --recursive
  - cd ..
  - ps: Start-FileDownload 'https://github.com/mesonbuild/meson/releases/download/0.45.1/meson-0.45.1-64.msi'
  - start /wait msiexec.exe /i meson-0.45.1-64.msi /quiet /qn /norestart /log install.log
  - cd SPMod
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - set PATH=C:\Program Files\Meson;%PATH%
  - mkdir build
  - cd build
  - meson .. . --buildtype plain
  - meson configure
  - ninja
